from collections import namedtuple

Posting = namedtuple('Posting', ['title', 'text'])

civil_engineering_intern = Posting('Civil Engineering Intern', """
The Bureau of Water & Sewer Operations is seeking to hire Civil Engineering Interns. The selected candidates will support various Divisions within BWSO and will be trained and will assist in research, investigations, studies or examinations related to the engineering functions of the department; assist in the preparation of maps, plans, and specifications; perform calculations; participate in field survey operations and receive training in the proper inspections of premises and the construction, maintenance, demolition or alteration of structures and equipment to ensure compliance with the provisions of laws, rules and regulations, and NYC DEP water and sewer design standards.
""")

inspector = Posting('Inspector', """
The Bureau of Water and Sewer Operation's Connections and Permitting Unit is seeking to hire five <mark>Civil Engineering Interns</mark> to serve as Inspectors. Under direct supervision, with little latitude for independent judgment, the selected candidates will perform engineering work of moderate difficulty and responsibility, but will not be limited to the following:   Conduct objective and thorough field inspections throughout the five boroughs to ensure methods of construction, and materials and workmanship used by the licensed plumbers or contractors fully conform to the current standards and specifications;  Maintain detailed and accurate records of inspections and reports, reports accurately on the events that transpire, secure and evaluate all facts and arrive at a sound conclusion  Develop detailed knowledge of all application and permit procedures related to water and sewer connections and installations.  Provide technical engineering support to other DEP units as necessary. Prepares oral and written reports as required.  Engages in studies, investigation or examinations related to the engineering functions or activities of the department, including the connection & Permitting.
""")

raw_inspector = Posting('Inspector', """
The Bureau of Water and Sewer Operation's Connections and Permitting Unit is seeking to hire five Civil Engineering Interns to serve as Inspectors. Under direct supervision, with little latitude for independent judgment, the selected candidates will perform engineering work of moderate difficulty and responsibility, but will not be limited to the following:   Conduct objective and thorough field inspections throughout the five boroughs to ensure methods of construction, and materials and workmanship used by the licensed plumbers or contractors fully conform to the current standards and specifications;  Maintain detailed and accurate records of inspections and reports, reports accurately on the events that transpire, secure and evaluate all facts and arrive at a sound conclusion  Develop detailed knowledge of all application and permit procedures related to water and sewer connections and installations.  Provide technical engineering support to other DEP units as necessary. Prepares oral and written reports as required.  Engages in studies, investigation or examinations related to the engineering functions or activities of the department, including the connection & Permitting.
""")
